GINGR_API_KEY = "GINGR_API_KEY"
GINGR_ROOT_APP = "GINGR_ROOT_APP"

INTUIT_CLIENT_ID = "INTUIT_CLIENT_ID"
INTUIT_CLIENT_SECRET = "INTUIT_CLIENT_SECRET"
INTUIT_REALM_ID = "INTUIT_REALM_ID"

INTUIT_ACCESS_TOKEN = "INTUIT_ACCESS_TOKEN"
